# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 16, 49, 11, 98617)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(related_name='tags', to='review.Question'),
        ),
    ]
