# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-12 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170401_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 20, 12, 57, 784841)),
        ),
    ]
